Makefile: Compile with -mabi=lp64d instead
Both nanhu and kunminghu cores are already supported RISC-V extension
of Double-precision floating-point instructions. So we can replace
-mabi=lp64 with -mabi=lp64d to enable related instructions in target
programs.

Otherwise compile error will happen if using CPU team's
toolchain which isn't compatible to lp64 (it's compiled with --with-abi-lp64d):

riscv64-unknown-linux-gnu-gcc -g -O0 -Wall -nostdlib -mcmodel=medany -mabi=lp64 -march=rv64imafdc -fno-PIE -fomit-frame-pointer -Wno-builtin-declaration-mismatch -ImyUser/include -I/home/ran/src/gos/include/uapi -c myUser/command/sct_test.c -o myUser/command/sct_test_c.o
In file included from /home/ran/toolchain/gcc12/riscv-toolchain-20230425/sysroot/usr/include/features.h:515,
                 from /home/ran/toolchain/gcc12/riscv-toolchain-20230425/sysroot/usr/include/printf.h:21,
                 from myUser/command/sct_test.c:3:
/home/ran/toolchain/gcc12/riscv-toolchain-20230425/sysroot/usr/include/gnu/stubs.h:14:11: fatal error: gnu/stubs-lp64.h: No such file or directory
   14 | # include <gnu/stubs-lp64.h>
      |           ^~~~~~~~~~~~~~~~~~

Signed-off-by: Ran Wang <wangran@bosc.ac.cn>