Add satp bare mode test
When the satp register is set to bare mode, accessing the mapped virtual address will cause an exception

Shell >> page_tlb_test satp_bare_test
Shell >> va value is : ===test===
read satp value:0x8000100000080155
write satp value:0x100000080155, set satp is bare mode
mhartid:0:
sbi_trap_error: Instruction access fault (error 18446744073709551615)
mcause: 0x1  mtval: 0x0
stval: 0x0
mepc: 0x0 mstatus : 0xa00000900
 gp : 0x0 tp : 0x600a000800000000 t0 : 0x800245a0
 t1 : 0x0 t2 : 0x0 t3 : 0x0
 s1 : 0x200000100 a0 : 0x0 a1 : 0x80024670
 a2 : 0x20 a3 : 0x0 a4 : 0x800109a8
 a5 : 0x0 a6 : 0x0 a7 : 0x201
 s2 : 0x80154658 s3 : 0x98c8 s4 : 0x2
 s5 : 0x100000080155 s6 : 0x0 s7 : 0x0
 s8 : 0x0 s9 : 0x0 s10: 0x0
 s11: 0x0 t3 : 0x0 t4: 0x0
 t5 : 0x0 t6 : 0x0 sp: 0x800244b8
 ra: 0x0
sbi panic...

Signed-off-by: yangyinglu <yangyinglu@bosc.cn>